CREATE DATABASE BOOKSTORE;
USE BOOKSTORE;

CREATE TABLE AUTHORS(
    ID PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) UNIQUE NOT NULL
);
CREATE TABLE PUBLISHERS(
    ID PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) UNIQUE NOT NULL
);
CREATE TABLE BOOKS(
    ID PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    SYNOPSIS VARCHAR(10000) NOT NULL,
    PRICE INT NOT NULL,
    OLD_PRICE INT,
    YEAR INT NOT NULL,
    ISSN INT UNIQUE NOT NULL
);

ALTER TABLE BOOKS ADD PUBLISHER_ID REFERENCES PUBLISHERS(ID);

CREATE TABLE BOOKS_AUTHORS(
    BOOK_ID FOREIGN KEY REFERENCES BOOK(ID),
    AUTHOR_ID FOREIGN KEY REFERENCES AUTHORS(ID)
);

