/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */


plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.springframework.boot").version("4.1.0-M1")
    id("io.spring.dependency-management").version("1.1.7")
    id("io.freefair.lombok").version("9.2.0")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:4.1.0-M1")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:4.1.0-M1")
    implementation("org.springframework.boot:spring-boot-starter-validation:4.1.0-M1")
    implementation("org.springframework.boot:spring-boot-starter-security-oauth2-resource-server:4.1.0-M2")

    // Production database client
    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.7")
    // Test database client
    testImplementation("com.h2database:h2:2.4.240")


    testImplementation("org.springframework.boot:spring-boot-starter-test:4.1.0-M1")
    
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.mindblow.bookstore.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
